[package]
name = "streamline"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
r2pipe = "0.7.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
